spring:
  config:
    import: optional:configserver:http://localhost:8001
  cloud:
    config:
      name: tenant-1
      #profile: dev
      #label: master
      fail-fast: false
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    username: 'sa'
    url: 'jdbc:h2:mem:db'
    password: ''
    name: 'tenant-1'

application:
  entity-id: hola
  encryption-key: hola
  configurations:
    - name: 'default-h2'
      url: 'jdbc:h2:mem:db'
      driver-class-name: 'org.h2.Driver'
      userName: 'sa'
      password: ''


