services:

  postgres:
    build:
      context: pg
      dockerfile: Dockerfile
      target: dev
    container_name: postgres-container
    hostname: postgres
    command: [ "postgres","-c", "wal_level=logical", "-c", "max_wal_senders=1" , "-c", "max_replication_slots=1" ]

    healthcheck:
      test: [ 'CMD','psql','-U','postgres','-c','SELECT 1' ]
      interval: 10s
      timeout: 5s
      retries: 5
    user: root
    ports:
      - "5432:5432"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ./tmp/pg:/var/lib/postgresql/data
    networks:
      - net-local

  key-cloak:
    hostname: localhost
    image: quay.io/keycloak/keycloak:26.1.3
    #user: root
    container_name: keycloak-container
    command:
      - start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - KC_DB=${KC_DB}
      - KC_DB_URL_HOST=${KC_DB_URL_HOST}
      - KC_DB_URL_PORT=${KC_DB_URL_PORT}
      - KC_DB_URL_DATABASE=${KC_DB_URL_DATABASE}
      - KC_DB_SCHEMA=${KC_DB_SCHEMA}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./tmp/keycloak:/opt/keycloak/data
    networks:
      - net-local
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  mongo-db:
    image: mongo:latest
    container_name: ${MONGO_NAME}
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ${MONGO_VOLUME}

  redis:
    image: redis:latest
    container_name: ${REDIS_NAME}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT_CLIENT}
    volumes:
      - ${REDIS_VOLUME}
    networks:
      - net-local
  server-ftp:
    build:
      context: ssh
      dockerfile: Dockerfile
    container_name: sftp-container
    #command: sleep infinity
    restart: always
    ports:
      - "2222:22"
    networks:
      - net-local


networks:
  net-local:
    driver: bridge
    name: net-local