spring:
  config:
    import: ${ENV_CLOUD_CONFIG_SERVER:optional:configserver:http://localhost:8001}
  cloud:
    config:
      name: landing-components
      profile: ${ENV_CLOUD_CONFIG_PROFILE:default}
      label: ${ENV_CLOUD_CONFIG_LABEL:master}
  cache:
    type:
    redis:
      time-to-live: 86400000
  data:
    redis:
      host: localhost
      port: 6379